### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by inquisitivecrystal** [Eaglestrike/lib#5]
# Logging
Currently, we perform all logging with `System.out.print` calls. This method is insufficient, and should be replaced with a coordinated logging facility, capable of logging both events and data and producing multiple types of output.

## Working plan
- [ ] Basic logging capability
    - [ ] Logging facility for events (in progress)
    - [ ] Logging facility for data (to track changes in variables over time)
- [ ] Add output capability
    - [ ] Print to console
    - [ ] Log to file
    - [ ] Send to external application
        - [ ] REST API
        - [ ] Client (probably in [electron](https://github.com/electron/electron))
